name: Main Deploy
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
permissions:
  id-token: write
  contents: write
  pull-requests: write
  pages: write

jobs:
  call-doc-deploy:
    uses: OGS-GmbH/reusable-github-actions/.github/workflows/doc-publish.yml@feat/doc-publish
